name: build-and-test-differential

on:
  pull_request:

jobs:
  build-and-test-differential:
    runs-on: ubuntu-latest
    container: ghcr.io/autowarefoundation/autoware-universe:latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

      - name: Install LTTng
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository ppa:lttng/stable-2.12
          sudo apt-get update
          sudo apt-get install -y lttng-tools lttng-modules-dkms liblttng-ust-dev
          sudo apt-get install -y python3-babeltrace python3-lttng
        shell: bash

      - name: Install depend packages
        run: |
          sudo apt-get update

          sudo apt-get install -y build-essential 
          sudo apt-get install -y cmake 
          sudo apt-get install -y git 
          sudo apt-get install -y python3-colcon-common-extensions 
          sudo apt-get install -y python3-flake8 
          sudo apt-get install -y python3-pip 
          sudo apt-get install -y python3-pytest-cov 
          sudo apt-get install -y python3-rosdep 
          sudo apt-get install -y python3-setuptools 
          sudo apt-get install -y python3-vcstool 
          sudo apt-get install -y wget

          # python3 -m pip install -U flake8-blind-except
          # python3 -m pip install -U flake8-blind-except
          # python3 -m pip install -U flake8-builtins
          # python3 -m pip install -U flake8-class-newline
          # python3 -m pip install -U flake8-comprehensions
          # python3 -m pip install -U flake8-deprecated
          # python3 -m pip install -U flake8-docstrings
          # python3 -m pip install -U flake8-import-order
          # python3 -m pip install -U flake8-quotes
          # python3 -m pip install -U pytest-repeat
          # python3 -m pip install -U pytest-rerunfailures
          # python3 -m pip install -U pytest
          # python3 -m pip install -U setuptools
          # python3 -m pip install -U colorcet

          # sudo apt-get install ros-galactic-desktop

          # sudo apt-get install -y graphviz \
          # sudo apt-get install -y graphviz-dev

          # python3 -m pip install -U pytest-mock
          # python3 -m pip install -U pybind11
          # python3 -m pip install -U bokeh
          # python3 -m pip install -U pandas-bokeh
          # python3 -m pip install -U jupyterlab
          # python3 -m pip install -U graphviz
        shell: bash


      - name: show pkg
        run: |
          dpkg -l | grep lttng

        shell: bash


      - name: Install Related package
        run: |
          sudo apt-get install -y ros-galactic-ros2trace 
          sudo apt-get install -y ros-galactic-ros2trace-analysis 
          sudo apt-get install -y ros-galactic-tracetools 
          sudo apt-get install -y ros-galactic-tracetools-analysis 
          sudo apt-get install -y ros-galactic-tracetools-launch 
          sudo apt-get install -y ros-galactic-tracetools-read 
          sudo apt-get install -y ros-galactic-tracetools-test 
          sudo apt-get install -y ros-galactic-tracetools-trace
        shell: bash

      - name: Build
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: galactic
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          build-depends-repos: build_depends.repos

      - name: Test
        id: test
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-test@v1
        with:
          rosdistro: galactic
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          build-depends-repos: build_depends.repos

      - name: Upload coverage to CodeCov
        if: ${{ steps.test.outputs.coverage-report-files != '' }}
        uses: codecov/codecov-action@v2
        with:
          files: ${{ steps.test.outputs.coverage-report-files }}
          fail_ci_if_error: false
          verbose: true

  clang-tidy-differential:
    runs-on: ubuntu-latest
    container: ros:galactic
    needs: build-and-test-differential
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

      - name: Run clang-tidy
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/clang-tidy@v1
        with:
          rosdistro: galactic
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          clang-tidy-config-url: https://raw.githubusercontent.com/autowarefoundation/autoware/main/.clang-tidy
          build-depends-repos: build_depends.repos
